In [6]:
import pandas as pd

DATA_DIR = 'C:\\git_repos\\Thesis\\Datasets\\aptos2019-blindness-detection\\train.csv'

# Load the data from the CSV file
data_df = pd.read_csv(DATA_DIR)

# Group by the diagnosis column
data_df = data_df.groupby("diagnosis")

# Sort each group by the diagnosis column
sorted_groups = {k: v.sort_values("diagnosis") for k, v in data_df}

# Split each group into two groups with a 90/10 split across each diagnosis
num_subgroups = 2
subgroups = {k: [] for k in sorted_groups.keys()}
for k, v in sorted_groups.items():
    group_size = len(v)
    # Calculate the size of the first subgroup (90%)
    subgroup_size_90 = int(group_size * 0.8)
    # Add 90% of the data to the first subgroup
    subgroups[k].append(v.iloc[:subgroup_size_90])
    # Add the remaining 10% of the data to the second subgroup
    subgroups[k].append(v.iloc[subgroup_size_90:])

# Combine subgroups from different diagnoses into the final groups
final_groups = []
for i in range(num_subgroups):
    final_group = pd.concat([subgroups[k][i] for k in sorted_groups.keys()])
    final_groups.append(final_group)

In [7]:
final_groups[0]

           id_code  diagnosis
3     002c21358ce6          0
2503  ad93d88c87ea          0
2502  ad6b07d5c338          0
2499  ad312ca98202          0
2497  ad20080452de          0
...            ...        ...
1455  6630f8675a97          4
1449  65e120143825          4
1446  65c958379680          4
1435  64fedbf97473          4
1432  64bad93fde3f          4

[2929 rows x 2 columns]

In [8]:
final_groups[1]

           id_code  diagnosis
1557  6d4f6c9a8406          0
1552  6d10709053ae          0
1550  6cffc6c6851a          0
1548  6cee2e148520          0
1545  6ccfdb031184          0
...            ...        ...
1274  58b866484a05          4
1251  576e189d23d4          4
1237  55eb405ec71e          4
1400  61e301bd3c25          4
3656  ff8a0b45c789          4

[733 rows x 2 columns]